package proyectofinaljara.Gui.Iu;

import javax.swing.JOptionPane;
import proyectofinaljara.Archivos;
import proyectofinaljara.objetos.*;

/**
 *
 * @author jara
 */
public class DialogCrearArma extends javax.swing.JDialog {
    Archivos<arma> archivosArmas;
    /**
     * Creates new form DialogCrearArma
     */
    public DialogCrearArma(java.awt.Frame parent, boolean modal, Archivos<arma> archivosArmas) {
        super(parent, modal);
        this.archivosArmas =archivosArmas;
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblCrear = new javax.swing.JLabel();
        lblNombreDelArma = new javax.swing.JLabel();
        txtNombreDelArma = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        ftxMuniciones = new javax.swing.JFormattedTextField();
        lblCalibre = new javax.swing.JLabel();
        ftxCalibre = new javax.swing.JFormattedTextField();
        lblPrecio = new javax.swing.JLabel();
        ftxPrecio = new javax.swing.JFormattedTextField();
        lblCalidad = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        lblValidar = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        lblMayoresA1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblBienvenida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBienvenida.setText("Bienvenido");

        lblCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrear.setText("Comienza a Crear:");

        lblNombreDelArma.setText("Nombre del Arma:");

        lblCantidad.setText("Cantidad de Municiones:");

        ftxMuniciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxMunicionesKeyTyped(evt);
            }
        });

        lblCalibre.setText("Calibre de Bala (mm):");

        ftxCalibre.setText("      ");
        ftxCalibre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxCalibreKeyTyped(evt);
            }
        });

        lblPrecio.setText("Precio:");

        ftxPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxPrecioKeyTyped(evt);
            }
        });

        lblCalidad.setText("Calidad:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básica", "Especial", "Épica", "Legendaria" }));

        lblValidar.setForeground(new java.awt.Color(255, 0, 0));
        lblValidar.setText("Todos los campos necesarios");

        botonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        lblMayoresA1.setForeground(new java.awt.Color(255, 0, 0));
        lblMayoresA1.setText("Solo números mayores a 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreDelArma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreDelArma))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBienvenida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMayoresA1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftxMuniciones, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCalibre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ftxCalibre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonCrear)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(ftxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValidar)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreDelArma)
                            .addComponent(txtNombreDelArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(ftxMuniciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxCalibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalibre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(ftxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalidad)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValidar))
                        .addGap(18, 18, 18)
                        .addComponent(botonCrear))
                    .addComponent(lblMayoresA1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxMunicionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxMunicionesKeyTyped
        // TODO add your handling code here:
        validarNumero(evt);
    }//GEN-LAST:event_ftxMunicionesKeyTyped

    private void ftxCalibreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxCalibreKeyTyped
        // TODO add your handling code here:
        validarNumero(evt);
    }//GEN-LAST:event_ftxCalibreKeyTyped

    private void ftxPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxPrecioKeyTyped
        // TODO add your handling code here:
        validarNumero(evt);
    }//GEN-LAST:event_ftxPrecioKeyTyped

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        if (ftxCalibre.getText().isEmpty() || ftxMuniciones.getText().isEmpty() || ftxPrecio.getText().isEmpty() || txtNombreDelArma.getText().isEmpty()) {
            lblValidar.setVisible(true);
        }else  if (Integer.parseInt(ftxCalibre.getText()) < 2 || Integer.parseInt(ftxMuniciones.getText()) < 2 || Integer.parseInt(ftxPrecio.getText()) < 2) {
            lblMayoresA1.setVisible(true);
        } else {
            arma arma =new arma(txtNombreDelArma.getText(), Integer.parseInt(ftxMuniciones.getText()), Integer.parseInt(ftxCalibre.getText()), comboBox.getSelectedItem().toString(), Integer.parseInt(ftxPrecio.getText()));
            try {
                archivosArmas.crearArchivo((arma)arma.clone(), "Arma", arma.getNombreDelArma() + "_" + arma.getCalidad(), ".arm");
                JOptionPane.showMessageDialog(this, "Creado");
                limpiar();
            } catch (CloneNotSupportedException ex) {
                System.out.println("No se puede clonar");
            }
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    public void limpiar() {
        txtNombreDelArma.setText("");
        ftxCalibre.setText("");
        ftxMuniciones.setText("");
        ftxPrecio.setText("");
        lblValidar.setVisible(false);
        lblMayoresA1.setVisible(false);
        comboBox.setSelectedIndex(0);
    }
    
    public void validarNumero(java.awt.event.KeyEvent evt){
        char value = evt.getKeyChar();
        if (value <'0' || value >'9') evt.consume();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JFormattedTextField ftxCalibre;
    private javax.swing.JFormattedTextField ftxMuniciones;
    private javax.swing.JFormattedTextField ftxPrecio;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCalibre;
    private javax.swing.JLabel lblCalidad;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblMayoresA1;
    private javax.swing.JLabel lblNombreDelArma;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblValidar;
    private javax.swing.JTextField txtNombreDelArma;
    // End of variables declaration//GEN-END:variables
}
