package proyectofinaljara.Gui.Iu;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import proyectofinaljara.Archivos;
import proyectofinaljara.objetos.*;
/**
 *
 * @author jara
 */
public class DialogTiendaArmas extends javax.swing.JDialog {
    private Archivos<arma> archivoArmas;
    private jugador jugador;
    private vehiculos vehiculoSeleccionado;
    private arma armaSeleccionada;
    private ObservableList<arma> observableListArmas;
    private ObservableList<vehiculos> observableListVehiculos;
    /**
     * Creates new form DialogTiendaArmas
     */
    public DialogTiendaArmas(java.awt.Frame parent, boolean modal, Archivos<arma> archivoArma, jugador jugador) {
        super(parent, modal);
        this.archivoArmas = archivoArma;
        this.jugador = jugador;
        this.observableListArmas = ObservableCollections.observableList(this.archivoArmas.leerListaDeArchivos(".arm"));
        this.observableListVehiculos  = ObservableCollections.observableList(jugador.getVehiculosEnBatallas());
        initComponents();
        botonComprar.setEnabled(false);
        this.txtOroDisponible.setText(Integer.toString(jugador.getOro()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblArmas = new javax.swing.JLabel();
        lblArmaSeleccionado = new javax.swing.JLabel();
        txtArmaSeleccionada = new javax.swing.JTextField();
        botonAgregarListadoArmas = new javax.swing.JButton();
        lblVehiculoSeleccionado = new javax.swing.JLabel();
        txtVehiculoSeleccionado = new javax.swing.JTextField();
        botonAgregarListadoVehiculos = new javax.swing.JButton();
        botonComprar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblOro = new javax.swing.JLabel();
        txtOroDisponible = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaArmas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablasVehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblArmas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblArmas.setText("Armas:");

        lblArmaSeleccionado.setText("Seleccionado:");

        txtArmaSeleccionada.setEditable(false);

        botonAgregarListadoArmas.setText("Agregar Listado");
        botonAgregarListadoArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarListadoArmasActionPerformed(evt);
            }
        });

        lblVehiculoSeleccionado.setText("Vehiculo:");

        txtVehiculoSeleccionado.setEditable(false);

        botonAgregarListadoVehiculos.setText("Agregar Listado");
        botonAgregarListadoVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarListadoVehiculosActionPerformed(evt);
            }
        });

        botonComprar.setText("Comprar");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        lblTotal.setText("Total:");

        txtTotal.setEditable(false);

        lblOro.setText("Oro:");

        txtOroDisponible.setEditable(false);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${observableListArmas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tablaArmas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreDelArma}"));
        columnBinding.setColumnName("Arma");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precio}"));
        columnBinding.setColumnName("Precio ");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${calidad}"));
        columnBinding.setColumnName("Calidad");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${armaSeleccionada}"), tablaArmas, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane3.setViewportView(tablaArmas);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${observableListVehiculos}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tablasVehiculos);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreVehiculo}"));
        columnBinding.setColumnName("Vehiculo");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${vehiculoSeleccionado}"), tablasVehiculos, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane4.setViewportView(tablasVehiculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArmas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblArmaSeleccionado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtArmaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonAgregarListadoArmas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonComprar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVehiculoSeleccionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehiculoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtOroDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonAgregarListadoVehiculos)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArmas)
                    .addComponent(lblOro)
                    .addComponent(txtOroDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArmaSeleccionado)
                    .addComponent(txtArmaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarListadoArmas)
                    .addComponent(lblVehiculoSeleccionado)
                    .addComponent(txtVehiculoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarListadoVehiculos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprar)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarListadoArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarListadoArmasActionPerformed
        // TODO add your handling code here:
        actualizarListaArmas(archivoArmas.leerListaDeArchivos(".arm"));
    }//GEN-LAST:event_botonAgregarListadoArmasActionPerformed

    private void botonAgregarListadoVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarListadoVehiculosActionPerformed
        // TODO add your handling code here:
        actualizarListadoVehiculos(jugador.getVehiculosEnBatallas());
    }//GEN-LAST:event_botonAgregarListadoVehiculosActionPerformed

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        // TODO add your handling code here:
        realizarCompra(armaSeleccionada, vehiculoSeleccionado);
    }//GEN-LAST:event_botonComprarActionPerformed

   private void actualizarListaArmas(List<arma> listaDeArmas) {
       this.observableListArmas.clear();
       this.observableListArmas.addAll(listaDeArmas);
   }
   private void actualizarListadoVehiculos(List<vehiculos> listaDeVehiculos) {
       this.observableListVehiculos.clear();
       this.observableListVehiculos.addAll(listaDeVehiculos);
   }

    public vehiculos getVehiculoSeleccionado() {
        return vehiculoSeleccionado;
    }

    public void setVehiculoSeleccionado(vehiculos vehiculoSeleccionado) {
        vehiculos previous = this.vehiculoSeleccionado;
        if(vehiculoSeleccionado != null){
            this.vehiculoSeleccionado = vehiculoSeleccionado;
            txtVehiculoSeleccionado.setText(this.vehiculoSeleccionado.getNombreVehiculo());
        }
        firePropertyChange("Vehiculo Seleccionado", previous, this.vehiculoSeleccionado);
    }

    private void realizarCompra(arma armaAComprar, vehiculos vehiculo) {
        try {
             if (jugador.getOro() >= armaAComprar.getPrecio() ) {
                jugador.setOro(jugador.getOro() - armaAComprar.getPrecio());
                vehiculo.agregarArmas(armaAComprar);
                JOptionPane.showMessageDialog(this, "Felicidades se ralizo la compra.");
                txtOroDisponible.setText(Integer.toString(jugador.getOro()));
            } else {
                JOptionPane.showMessageDialog(this, "Lo siento no se ralizo la compra. \nOro Insuficiente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lo siento no has seleccionado un vehiculo o arma.");
        }
           
    }
    
    public arma getArmaSeleccionada() {
        return armaSeleccionada;
    }

    public void setArmaSeleccionada(arma armaSeleccionada) {
        arma previous = this.armaSeleccionada;
        if(armaSeleccionada != null){
            try {
                this.armaSeleccionada = (arma) armaSeleccionada.clone();
                txtArmaSeleccionada.setText(this.armaSeleccionada.getNombreDelArma());
                txtTotal.setText(Integer.toString(armaSeleccionada.getPrecio()));
                botonComprar.setEnabled(true);
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(DialogCargarJuego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        firePropertyChange("Arma Seleccionado", previous, this.vehiculoSeleccionado);
    }

    public ObservableList<arma> getObservableListArmas() {
        return observableListArmas;
    }

    public void setObservableListArmas(ObservableList<arma> observableListArmas) {
        this.observableListArmas = observableListArmas;
    }

    public ObservableList<vehiculos> getObservableListVehiculos() {
        return observableListVehiculos;
    }

    public void setObservableListVehiculos(ObservableList<vehiculos> observableListVehiculos) {
        this.observableListVehiculos = observableListVehiculos;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarListadoArmas;
    private javax.swing.JButton botonAgregarListadoVehiculos;
    private javax.swing.JButton botonComprar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblArmaSeleccionado;
    private javax.swing.JLabel lblArmas;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVehiculoSeleccionado;
    private javax.swing.JTable tablaArmas;
    private javax.swing.JTable tablasVehiculos;
    private javax.swing.JTextField txtArmaSeleccionada;
    private javax.swing.JTextField txtOroDisponible;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVehiculoSeleccionado;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
