package proyectofinaljara.Gui.Iu;

import com.sun.javafx.scene.SceneHelper;
import java.awt.Frame;
import proyectofinaljara.Archivos;
import proyectofinaljara.crearEscenarios;
import proyectofinaljara.Gui.Iu.*;
import proyectofinaljara.objetos.*;

/**
 *
 * @author jara
 */
public class DialogoNuevoJuego extends javax.swing.JDialog {
    private jugador jugadorNuevo;
    private FrameEscritorio frameEscritorio;
    private CrearVehiculoDialog crearVehiculoDialog;
    private Archivos<escenarios> archivoEscenario;
    private Archivos<vehiculos> archivoVehiculos;
    private Archivos<jugador> archivoJugador;
    private Archivos<arma> archivoArmas;
    /**
     * Creates new form DialogNuevoJuego
     */
    public DialogoNuevoJuego(java.awt.Frame parent, boolean modal, Archivos<escenarios> archivoEscenario, Archivos<vehiculos> archivoVehiculos, Archivos<jugador> archivoJugador, FrameEscritorio frameEscritorio, Archivos<arma> archivoArmas) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.archivoArmas =archivoArmas;
        this.frameEscritorio = frameEscritorio;
        this.archivoJugador = archivoJugador;
        this.archivoEscenario = archivoEscenario;
        this.archivoVehiculos = archivoVehiculos;
        lblVacio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblIngresaNombre = new javax.swing.JLabel();
        txtNombreJugador = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();
        lblVacio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblBienvenido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido:");

        lblIngresaNombre.setText("Ingresa el Nombre: ");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        lblVacio.setForeground(new java.awt.Color(255, 0, 0));
        lblVacio.setText("Campo Vacio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(botonCrear)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngresaNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreJugador))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVacio)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBienvenido)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresaNombre)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVacio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrear)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        if (txtNombreJugador.getText().isEmpty()) {
            lblVacio.setVisible(true);
        }
        lblVacio.setVisible(false);
        jugadorNuevo = new jugador(txtNombreJugador.getText());
        txtNombreJugador.setText("");
        this.setVisible(false);
        for (int i = 0; i < 3; i++) {
            crearVehiculoDialog = new CrearVehiculoDialog((Frame) this.getParent(), true, jugadorNuevo, archivoVehiculos, archivoArmas);
            crearVehiculoDialog.setVisible(true);
            guardarJugador();
        }
        frameEscritorio.setJugador(jugadorNuevo);
        this.setVisible(false);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void guardarJugador() {
        archivoJugador.crearArchivo(jugadorNuevo, "Jugador", jugadorNuevo.getNombreJugador(), ".jdr");
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblIngresaNombre;
    private javax.swing.JLabel lblVacio;
    private javax.swing.JTextField txtNombreJugador;
    // End of variables declaration//GEN-END:variables
}
