package proyectofinaljara.Gui.Iu;

import proyectofinaljara.Archivos;
import proyectofinaljara.objetos.*;
/**
 *
 * @author jara
 */
public class DialogTiendaOpciones extends javax.swing.JDialog {
    private DialogTiendaVehiculos dialogTiendaVehiculos;
    private DialogTiendaArmas dialogTiendaArmas;
    private DialogTiendaMuniciones dialogTiendaMuniciones;
    /**
     * Creates new form DialogTienda
     */
    public DialogTiendaOpciones(java.awt.Frame parent, boolean modal, jugador jugador, Archivos<vehiculos> archivoVehiculos, Archivos<arma> archivoArma) {
        super(parent, modal);
        dialogTiendaVehiculos =  new DialogTiendaVehiculos(parent, true, jugador, archivoVehiculos);
        dialogTiendaArmas  = new DialogTiendaArmas(parent, true, archivoArma, jugador);
        dialogTiendaMuniciones = new DialogTiendaMuniciones(parent, true, jugador);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTienda = new javax.swing.JLabel();
        botonVehiculos = new javax.swing.JButton();
        botonArmas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTienda.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTienda.setText("Tienda:");

        botonVehiculos.setText("Vehiculos");
        botonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculosActionPerformed(evt);
            }
        });

        botonArmas.setText("Armas");
        botonArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArmasActionPerformed(evt);
            }
        });

        jButton1.setText("Municiones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblTienda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1)
                            .addComponent(botonVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonArmas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonArmas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dialogTiendaVehiculos.setVisible(true);
    }//GEN-LAST:event_botonVehiculosActionPerformed

    private void botonArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArmasActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        dialogTiendaArmas.setVisible(true);
    }//GEN-LAST:event_botonArmasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        dialogTiendaMuniciones.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArmas;
    private javax.swing.JButton botonVehiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblTienda;
    // End of variables declaration//GEN-END:variables
}
