package proyectofinaljara.Gui.Iu;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import proyectofinaljara.objetos.*;
/**
 *
 * @author jara
 */
public class DialogTiendaMuniciones extends javax.swing.JDialog {
    private jugador jugador;
    private vehiculos vehiculoSeleccionado;
    private arma armaSeleccionada;
    private List<arma> listaArmas;
    private int precioUnitario;
    private int total;
    private ObservableList<vehiculos> observableListVehiculo;
    private ObservableList<arma> observableListArma;
    
    /**
     * Creates new form DialogTiendaMuniciones
     */
    public DialogTiendaMuniciones(java.awt.Frame parent, boolean modal, jugador jugador) {
        super(parent, modal);
        this.jugador = jugador;
        this.listaArmas = new ArrayList<>();
        this.observableListVehiculo = ObservableCollections.observableList(jugador.getVehiculosEnBatallas());
        this.observableListArma = ObservableCollections.observableList(listaArmas);
        initComponents();
        this.setLocationRelativeTo(null);
        this.botonAgregarListadoArma.setEnabled(false);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblMuniciones = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        txtVehiculoSeleccionado = new javax.swing.JTextField();
        lblArma = new javax.swing.JLabel();
        txtArmaSeleccionada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        botonAgregarListadoVehiculo = new javax.swing.JButton();
        botonAgregarListadoArma = new javax.swing.JButton();
        lblNumeroMuniciones = new javax.swing.JLabel();
        txtMunicionesNumeros = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        botonComprar = new javax.swing.JButton();
        botonSubTotal = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMuniciones.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMuniciones.setText("Municiones:");

        lblVehiculo.setText("Vehiculo:");

        txtVehiculoSeleccionado.setEditable(false);

        lblArma.setText("Arma:");

        txtArmaSeleccionada.setEditable(false);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${observableListVehiculo}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreVehiculo}"));
        columnBinding.setColumnName("Vehiculo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${vehiculoSeleccionado}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTable1);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${observableListArma}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreDelArma}"));
        columnBinding.setColumnName("Arma");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${municiones}"));
        columnBinding.setColumnName("Municiones");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${calidad}"));
        columnBinding.setColumnName("Calidad");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${armaSeleccionada}"), jTable2, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jTable2);

        botonAgregarListadoVehiculo.setText("Agregar Listado");
        botonAgregarListadoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarListadoVehiculoActionPerformed(evt);
            }
        });

        botonAgregarListadoArma.setText("Agregar Listado");
        botonAgregarListadoArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarListadoArmaActionPerformed(evt);
            }
        });

        lblNumeroMuniciones.setText("Municiones:");

        txtMunicionesNumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMunicionesNumerosKeyTyped(evt);
            }
        });

        lblTotal.setText("Total:");

        txtTotal.setEditable(false);

        botonComprar.setText("Comprar");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        botonSubTotal.setText("Sub Total");
        botonSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubTotalActionPerformed(evt);
            }
        });

        lblPrecio.setText("Precio Unitario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMuniciones)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehiculoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(botonAgregarListadoVehiculo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblArma)
                                .addGap(18, 18, 18)
                                .addComponent(txtArmaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonAgregarListadoArma))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(botonSubTotal))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblNumeroMuniciones)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtMunicionesNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTotal)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPrecio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPrecioUnitario))))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuniciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(txtVehiculoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArma)
                    .addComponent(txtArmaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarListadoVehiculo)
                    .addComponent(botonAgregarListadoArma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroMuniciones)
                    .addComponent(txtMunicionesNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonComprar)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSubTotal)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMunicionesNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunicionesNumerosKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if (value <'0' || value >'9') evt.consume();
    }//GEN-LAST:event_txtMunicionesNumerosKeyTyped

    private void botonAgregarListadoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarListadoVehiculoActionPerformed
        // TODO add your handling code here:
        actualizarListadoVehiculo(jugador.getVehiculosEnBatallas());
    }//GEN-LAST:event_botonAgregarListadoVehiculoActionPerformed

    private void botonAgregarListadoArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarListadoArmaActionPerformed
        // TODO add your handling code here:
        actualizarListadoArma(vehiculoSeleccionado.getArmas());
    }//GEN-LAST:event_botonAgregarListadoArmaActionPerformed

    private void botonSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubTotalActionPerformed
        // TODO add your handling code here:
        total = precioUnitario*(Integer.parseInt(txtMunicionesNumeros.getText()));
        txtTotal.setText(Integer.toString(total));
    }//GEN-LAST:event_botonSubTotalActionPerformed

    private void limpiar() {
        txtPrecioUnitario.setText("");
        txtTotal.setText("");
        txtMunicionesNumeros.setText("");
    }
    
    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        // TODO add your handling code here:
        if (jugador.getOro() >= total) {
            jugador.setOro(jugador.getOro()-total);
            armaSeleccionada.setMuniciones(armaSeleccionada.getMuniciones()+(Integer.parseInt(txtMunicionesNumeros.getText())));
            JOptionPane.showMessageDialog(this, "Felicidades se ralizo la compra.");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Lo siento no se realizo la compra.\nOro Insuficiente.");
        }
    }//GEN-LAST:event_botonComprarActionPerformed

    private void actualizarListadoVehiculo(List<vehiculos> listadoVehiculo) {
        this.observableListVehiculo.clear();
        this.observableListVehiculo.addAll(listadoVehiculo);
    }
    
    private void actualizarListadoArma(List<arma> listArmas) {
        this.observableListArma.clear();
        this.observableListArma.addAll(listArmas);
    }

    public vehiculos getVehiculoSeleccionado() {
        return vehiculoSeleccionado;
    }

    public void setVehiculoSeleccionado(vehiculos vehiculoSeleccionado) {
        vehiculos previous = this.vehiculoSeleccionado;
        if(vehiculoSeleccionado != null){
            this.vehiculoSeleccionado = vehiculoSeleccionado;
            txtVehiculoSeleccionado.setText(this.vehiculoSeleccionado.getNombreVehiculo());
            botonAgregarListadoArma.setEnabled(true);
        }
        firePropertyChange("Vehiculo Seleccionado", previous, this.vehiculoSeleccionado);
    }

    public arma getArmaSeleccionada() {
        return armaSeleccionada;
    }

    public void setArmaSeleccionada(arma armaSeleccionada) {
        arma anterior =  this.armaSeleccionada;
        if (armaSeleccionada != null) {
            this.armaSeleccionada  = armaSeleccionada;
            precioUnitario = (armaSeleccionada.getCalibreDeBala()*armaSeleccionada.comprobarCalidad(armaSeleccionada.getCalidad())/10);
            txtArmaSeleccionada.setText(this.armaSeleccionada.getNombreDelArma());
            txtPrecioUnitario.setText(Integer.toString(precioUnitario));
        }
        firePropertyChange("Arma Seleccionada", anterior, this.armaSeleccionada);
    }

    public ObservableList<vehiculos> getObservableListVehiculo() {
        return observableListVehiculo;
    }

    public void setObservableListVehiculo(ObservableList<vehiculos> observableListVehiculo) {
        this.observableListVehiculo = observableListVehiculo;
    }

    public ObservableList<arma> getObservableListArma() {
        return observableListArma;
    }

    public void setObservableListArma(ObservableList<arma> observableListArma) {
        this.observableListArma = observableListArma;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarListadoArma;
    private javax.swing.JButton botonAgregarListadoVehiculo;
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonSubTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblArma;
    private javax.swing.JLabel lblMuniciones;
    private javax.swing.JLabel lblNumeroMuniciones;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTextField txtArmaSeleccionada;
    private javax.swing.JTextField txtMunicionesNumeros;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVehiculoSeleccionado;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
