package proyectofinaljara.Gui.Iu;

import proyectofinaljara.objetos.*;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import proyectofinaljara.Archivos;

/**
 *
 * @author jara
 */
public class FrameMenu extends javax.swing.JInternalFrame {
    private DialogCrearArma crearArma;
    private DialogoPedirEscenario pedirEscenario;
    private DialogTiendaOpciones dialogTiendaOpciones;
    private JDesktopPane panelDeEscritorio;
    private JFrame framePrincipal;
    private jugador jugador;
    private Archivos<vehiculos> archivoVehiculos;
    private Archivos<arma> archivosArmas;
    private Archivos<escenarios> archivoEscenario;
    /**
     * Creates new form MenuPrincipalFrame
     */
    public FrameMenu(JFrame framePrincipal, Archivos<escenarios> archivoEscenario, Archivos<arma> archivosArmas, JDesktopPane panelDeEscritorio, Archivos<vehiculos> archivoVehiculos, jugador jugador) {
        initComponents();
        this.jugador = jugador;
        this.archivoVehiculos = archivoVehiculos;
        this.archivosArmas = archivosArmas;
        this.archivoEscenario = archivoEscenario;
        crearArma = new DialogCrearArma(framePrincipal, true, archivosArmas);
        this.panelDeEscritorio = panelDeEscritorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        butonBatalla = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonTienda = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonBatalla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butonBatalla.setText("Batalla");
        butonBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBatallaActionPerformed(evt);
            }
        });
        panel.add(butonBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        botonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        panel.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        botonTienda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonTienda.setText("Tienda");
        botonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaActionPerformed(evt);
            }
        });
        panel.add(botonTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        botonReportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonReportes.setText("Reportes");
        panel.add(botonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        panel.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinaljara/Gui/imagenes/paneInicio.jpg"))); // NOI18N
        panel.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaActionPerformed
        // TODO add your handling code here:
        dialogTiendaOpciones  = new DialogTiendaOpciones(framePrincipal, true, jugador, archivoVehiculos, archivosArmas);
        this.setVisible(false);
        dialogTiendaOpciones.setVisible(true);
    }//GEN-LAST:event_botonTiendaActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        crearArma.setVisible(true);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void butonBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonBatallaActionPerformed
        // TODO add your handling code here:
        this.pedirEscenario = new DialogoPedirEscenario(framePrincipal, true, archivoEscenario, panelDeEscritorio, jugador);
        this.setVisible(false);
        pedirEscenario.setVisible(true);
    }//GEN-LAST:event_butonBatallaActionPerformed

    public void setJugador(jugador jugador) {
        this.jugador = jugador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTienda;
    private javax.swing.JButton butonBatalla;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
