package proyectofinaljara.Gui.Iu;

import java.awt.Frame;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyectofinaljara.objetos.*;
/**
 *
 * @author jara
 */
public class FrameBatalla extends javax.swing.JInternalFrame {
    private String direccion;
    private int posicionX;
    private int posicionY;
    private vehiculos vehiculo;
    private batalla batalla;
    private arma armaSeleccionada;
    private movimientos generarMovimiento;
    private escenarios escenario;
    private int valorDado;
    private JLabel matrizLbl[][];
    private jugador jugador;
    private DialogArmas dialogArmas;
    private DialogSeleccionarVehiculo dialogSeleccionarVehiculo;
    private java.awt.Frame parent;
    /**
     * Creates new form FrameJuego
     */
    public FrameBatalla(escenarios escenario, jugador jugador, java.awt.Frame parent) {
        initComponents();
        this.parent =parent;
        this.jugador = jugador;
        this.escenario = escenario;
        matrizLbl =  new JLabel[escenario.getValorM()][escenario.getValorN()];
        buscarPosicionJugador();
        limpiar();
        desactivarYActivar(1, true);
        agregarLabels();
        this.batalla = new batalla(jugador, vehiculo, escenario, this, posicionX, posicionY);
        botonAccion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDesc = new javax.swing.JPanel();
        lblTurnos = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblTurnoJugadorOEnemigo = new javax.swing.JLabel();
        lblAccion = new javax.swing.JLabel();
        comboAccion = new javax.swing.JComboBox<>();
        lblVehiculoEnTurno = new javax.swing.JLabel();
        lblImagenVehiculo = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        botonArriba = new javax.swing.JButton();
        botonDerecha = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();
        botonAbajo = new javax.swing.JButton();
        lblCasillas = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        ftxCasiilas = new javax.swing.JFormattedTextField();
        botonAccion = new javax.swing.JButton();
        lblValidar = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JTextField();
        lblDado = new javax.swing.JLabel();
        botonLanzarDado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelJuego = new javax.swing.JPanel();

        setResizable(true);

        lblTurnos.setText("Turno:");

        lblVehiculo.setText("Vehículo:");

        lblAccion.setText("Acciones: ");

        comboAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moverse", "Atacar Enemigo", "Atacar Terreno", "Aplicar Objeto", "Cambiar de Vehiculo", "Rendirse" }));

        lblDireccion.setText("Dirección:*");

        botonArriba.setText("↑");
        botonArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaActionPerformed(evt);
            }
        });

        botonDerecha.setText("→");
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        botonIzquierda.setText("←");
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });

        botonAbajo.setText("↓");
        botonAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoActionPerformed(evt);
            }
        });

        lblCasillas.setText("Casillas:*");

        lblDescripcion.setText("Descripción:");

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        ftxCasiilas.setEditable(false);
        ftxCasiilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxCasiilasKeyTyped(evt);
            }
        });

        botonAccion.setText("Generar Acción");
        botonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAccionActionPerformed(evt);
            }
        });

        lblValidar.setForeground(new java.awt.Color(255, 0, 0));
        lblValidar.setText("Todos los campos con * son obligatorios");

        lblAtaque.setText("Ataque:*");

        txtAtaque.setEditable(false);

        lblDado.setBackground(java.awt.SystemColor.activeCaption);
        lblDado.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)), new javax.swing.border.MatteBorder(null)));

        botonLanzarDado.setText("Lanzar Dado");
        botonLanzarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLanzarDadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDescLayout = new javax.swing.GroupLayout(panelDesc);
        panelDesc.setLayout(panelDescLayout);
        panelDescLayout.setHorizontalGroup(
            panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescLayout.createSequentialGroup()
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurnos)
                            .addComponent(lblVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTurnoJugadorOEnemigo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(lblVehiculoEnTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelDescLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblImagenVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDescLayout.createSequentialGroup()
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValidar)
                            .addGroup(panelDescLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(botonAccion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonLanzarDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDescLayout.createSequentialGroup()
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccion)
                            .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonIzquierda)
                                .addComponent(lblDireccion))
                            .addComponent(lblCasillas)
                            .addComponent(lblAtaque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDescLayout.createSequentialGroup()
                                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonArriba)
                                    .addGroup(panelDescLayout.createSequentialGroup()
                                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtAtaque, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ftxCasiilas, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonAbajo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonDerecha)))
                                .addGap(56, 56, 56)
                                .addComponent(lblDado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelDescLayout.setVerticalGroup(
            panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDescLayout.createSequentialGroup()
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTurnos)
                            .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAccion)
                                .addComponent(lblDescripcion))
                            .addComponent(lblTurnoJugadorOEnemigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDescLayout.createSequentialGroup()
                                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVehiculo)
                                    .addComponent(lblVehiculoEnTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(lblImagenVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDescLayout.createSequentialGroup()
                                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDescLayout.createSequentialGroup()
                                        .addComponent(lblDireccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(botonIzquierda)
                                            .addComponent(botonAbajo)
                                            .addComponent(botonDerecha)))
                                    .addComponent(botonArriba))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCasillas)
                                    .addComponent(ftxCasiilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAtaque)
                                    .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValidar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDescLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelDescLayout.createSequentialGroup()
                                .addComponent(lblDado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonLanzarDado)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panelJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setArmaSeleccionada(arma armaSeleccionada) {
        this.armaSeleccionada = armaSeleccionada;
    }

    public arma getArmaSeleccionada() {
        return armaSeleccionada;
    }

    public vehiculos getVehiculo() {
        return vehiculo;
    }

    public void setVehiculo(vehiculos vehiculo) {
        this.vehiculo = vehiculo;
        lblVehiculoEnTurno.setText(vehiculo.getNombreVehiculo());
        lblValidar.setVisible(false);
        if (vehiculo instanceof avion) {
            lblImagenVehiculo.setIcon(new ImageIcon("Imagenes/Avion.png"));
        } else {
            lblImagenVehiculo.setIcon(new ImageIcon("Imagenes/Tanque.png"));
        }
    }
    
    private void buscarPosicionJugador() {
        for (int i = 0; i < escenario.getValorM(); i++) {
            for (int j = 0; j < escenario.getValorN(); j++) {
                if (escenario.getTerrenos()[i][j] == 4) {
                    posicionX = i;
                    posicionY = j;
                    break;
                }
            }
        }
    }
    
    private void agregarLabels() {
        for (int i = 0; i < escenario.getValorM(); i++) {
            for (int j = 0; j < escenario.getValorN(); j++) {
                matrizLbl[i][j] = new JLabel();
                matrizLbl[i][j].setSize(118, 57);
                matrizLbl[i][j].setLocation(40+(i*125), 35+(j*65));
                escenario.asignarColorImprimir(i, j, 1, matrizLbl, escenario.getTerrenos());
                matrizLbl[i][j].setVisible(true);
                panelJuego.add(matrizLbl[i][j]);
            }
        }
    }
    
    private int casoDireccion(String caso) {
        switch (caso) {
            case "Arriba":
                return 3;
            case "Abajo":
                return 4;
            case "Izquierda":
                return 1;
            case "Derecha":
                return 2;
            default:
                throw new AssertionError();
        }
    }
    
    private void botonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccionActionPerformed
        // TODO add your handling code here:
        if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Moverse")) {
            buscarPosicionJugador();
           Runnable runTower = new movimientos(vehiculo, posicionX, posicionY, 1, casoDireccion(direccion), escenario.getTerrenos(), matrizLbl, valorDado);
           Thread thread = new Thread(runTower);
           thread.start();
        } else if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Atacar Enemigo")) {
            dialogArmas = new DialogArmas(parent, true, vehiculo, this);
            dialogArmas.setVisible(true);
            batalla.setVehiculoSeleccionado(vehiculo);
            buscarPosicionJugador();
            batalla.setPosicionJugadorX(posicionX);
            batalla.setPosicionJugadorY(posicionY);
            batalla.atacarEnemigoYJugador(1, false, casoDireccion(direccion), armaSeleccionada, valorDado, matrizLbl);
        } else if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Atacar Terreno")) {
            
        } else if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Aplicar Objeto")) {
            
        } else  if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Cambiar de Vehículo")) {
            dialogSeleccionarVehiculo = new DialogSeleccionarVehiculo(parent, true, jugador, this);
            dialogSeleccionarVehiculo.setVisible(true);
        } else {
            this.setVisible(false);
        }
        turnos(2);
    }//GEN-LAST:event_botonAccionActionPerformed

    private void activarBotones(boolean activado){
        botonAbajo.setEnabled(activado);
        botonArriba.setEnabled(activado);
        botonDerecha.setEnabled(activado);
        botonIzquierda.setEnabled(activado);
        botonLanzarDado.setEnabled(activado);
        botonAccion.setEnabled(activado);
    }
    
    private void turnos(int numero) {
        if (batalla.comprobarEnemigosEnEscenario()) {
            batalla.comprobacionFinDeJuego(2, true);
        } else {
             switch (numero) {
            case 1:
                activarBotones(true);
                lblTurnoJugadorOEnemigo.setText(jugador.getNombreJugador());
                batalla.comprobarSiAunTieneVehiculosDisponibles();
                break;
            case 2:
                activarBotones(false);
                lblTurnoJugadorOEnemigo.setText("Enemigo");
                JOptionPane.showMessageDialog(this, "Turno de Enemigos");
                batalla.comprobarSiAunTieneVehiculosDisponibles();
                batalla.ataqueEnemigos(matrizLbl);
                turnos(1);
                break;
            default:
        }
        }
       
    }
    
    private void desactivarYActivar(int caso, boolean activado){
        switch (caso) {
            case 1://Solo se activa el comboBox
                comboAccion.setEnabled(activado);
                if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Atacar Enemigo") || comboAccion.getSelectedItem().toString().equalsIgnoreCase("Moverse") || comboAccion.getSelectedItem().toString().equalsIgnoreCase("Atacar Terreno")) {
                    activarBotones(true);
                }
                break;
            case 2://Se desactivan todos turno enemigo
                comboAccion.setEnabled(activado);
                activarBotones(activado);
                break;
            default:
                throw new AssertionError();
        }
    }
    
    private void agregarArma(){
        dialogArmas = new DialogArmas((Frame)this.getParent(), true, vehiculo, this);
        dialogArmas.setVisible(true);
    }
    
    private void agregarValorDado(int valor){
        if (valor < 10) {
            lblDado.setText("   " + valor + "   ");
        } else if (valor >= 10 && valor < 100) {
            lblDado.setText("  " + valor + "  ");
        } else {
            lblDado.setText(" " + valor);
        }
    }
    
    public void limpiar() {
        lblValidar.setVisible(false);
    }
    
    public void moverse() {
        if (direccion == null ) {
            lblValidar.setVisible(true);
        } else {
            
        }
    }
    
    public void atacarEnemigo() {
        
    }
    
    public void atacarTerrno() {

    }
    
    public void aplicarObjeto() {
        
    }
    
    public void cambiarVehiculo() {
        
    }
    
    public void rendirse() {
        this.setVisible(false);
    }

    public void setEscenario(escenarios escenario) {
        this.escenario = escenario;
    }
    
    private void botonArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaActionPerformed
        // TODO add your handling code here:
        direccion = "Arriba";
        agregarTexto("Dirección: Arriba");
    }//GEN-LAST:event_botonArribaActionPerformed

    private void botonAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoActionPerformed
        // TODO add your handling code here:
        direccion = "Abajo";
        agregarTexto("Dirección: Abajo");
    }//GEN-LAST:event_botonAbajoActionPerformed

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        // TODO add your handling code here:
        direccion = "Izquierda";
        agregarTexto("Dirección: Izquierda");
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        // TODO add your handling code here:
        direccion = "Derecha";
        agregarTexto("Dirección: Derecha");
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void ftxCasiilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxCasiilasKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if (value <'0' || value >'9') evt.consume();
    }//GEN-LAST:event_ftxCasiilasKeyTyped

    private void botonLanzarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLanzarDadoActionPerformed
        // TODO add your handling code here:
        Random random = new Random(); 
        Runnable thread = () -> {
            try {
                for (int i = 0; i < 5; i++) {
                    Thread.sleep(1000);
                    if (comboAccion.getSelectedItem().toString().equalsIgnoreCase("Moverse")) {
                        valorDado = random.nextInt(6) +1;
                    } else {
                         valorDado = random.nextInt(100) +1;
                    }
                    agregarValorDado(valorDado);
                }
                comboAccion.setEnabled(true);
                botonAccion.setEnabled(true);
            } catch (InterruptedException ex) {
                
            }
        };
        Thread hilo = new Thread(thread);
        hilo.start();
    }//GEN-LAST:event_botonLanzarDadoActionPerformed

    public void agregarTexto(String agregar){
        areaTexto.setText(areaTexto.getText()+ "\n" + agregar + "\n");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botonAbajo;
    private javax.swing.JButton botonAccion;
    private javax.swing.JButton botonArriba;
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JButton botonLanzarDado;
    private javax.swing.JComboBox<String> comboAccion;
    private javax.swing.JFormattedTextField ftxCasiilas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblCasillas;
    private javax.swing.JLabel lblDado;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblImagenVehiculo;
    private javax.swing.JLabel lblTurnoJugadorOEnemigo;
    private javax.swing.JLabel lblTurnos;
    private javax.swing.JLabel lblValidar;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JLabel lblVehiculoEnTurno;
    private javax.swing.JPanel panelDesc;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JTextField txtAtaque;
    // End of variables declaration//GEN-END:variables
}
